version: "3.2"
services:
  hotels:
    image: hotels
    container_name: 'hotels'
    ports:
      - "8081:8081"
    networks:
      - data-service-network

  flight:
    image: flight
    container_name: 'flight'
    ports:
      - "8080:8080"
    networks:
      - data-service-network
    depends_on:
      - hotels

  frontend-hotels:
    image: frontend-hotels
    container_name: 'frontend-hotels'
    ports:
      - "4000:4000"
    networks:
      - data-service-network

  frontend-flight:
    image: frontend-flight
    container_name: 'frontend-flight'
    ports:
      - "3000:3000"
    networks:
      - data-service-network
    depends_on:
      - frontend-hotels
networks:
  data-service-network: {}