version: "3.2"
services:
  hotels:
    image: hotels
    container_name: 'hotels'
    ports:
      - "8081:8081"
    networks:
      - data-service-network

  flight:
    image: flight
    container_name: 'flight'
    ports:
      - "8080:8080"
    networks:
      - data-service-network
    depends_on:
      - hotels
networks:
  data-service-network: {}